card_list: dict = {
    "1": {
        "card_meaning": "İlham, güç, yaratma, başlangıçlar, potansiyel",
        "card_name": "Ace of Wands",
        "card_url": "http://www.tarotlore.com/tarot-cards/ace-of-wands/",
        "card_img": "http://i.imgur.com/MfJ1s77.jpg",
    },
    "10": {
        "card_meaning": "Yük, sorumluluk, sıkı çalışma, stres, başarı",
        "card_name": "Ten of Wands",
        "card_url": "http://www.tarotlore.com/tarot-cards/ten-of-wands/",
        "card_img": "http://i.imgur.com/hNC3y5g.jpg",
    },
    "11": {
        "card_meaning": "Coşku, keşif, keşif, özgür ruh",
        "card_name": "Page of Wands",
        "card_url": "http://www.tarotlore.com/tarot-cards/page-of-wands/",
        "card_img": "http://i.imgur.com/44puitP.jpg",
    },
    "12": {
        "card_meaning": "Enerji, tutku, şehvet, aksiyon, macera, dürtüsellik",
        "card_name": "Knight of Wands",
        "card_url": "http://www.tarotlore.com/tarot-cards/knight-of-wands/",
        "card_img": "http://i.imgur.com/yzCPXQX.jpg",
    },
    "13": {
        "card_meaning": "Coşku, sıcaklık, canlılık, kararlılık",
        "card_name": "Queen of Wands",
        "card_url": "http://www.tarotlore.com/tarot-cards/queen-of-wands/",
        "card_img": "http://i.imgur.com/LTeYFqy.jpg",
    },
    "14": {
        "card_meaning": "Doğuştan lider, vizyon, girişimci, onur",
        "card_name": "King of Wands",
        "card_url": "http://www.tarotlore.com/tarot-cards/king-of-wands/",
        "card_img": "http://i.imgur.com/iC2Il8N.jpg",
    },
    "15": {
        "card_meaning": "Ham güç, zafer, atılımlar, zihinsel netlik",
        "card_name": "Ace of Swords",
        "card_url": "http://www.tarotlore.com/tarot-cards/ace-of-swords/",
        "card_img": "http://i.imgur.com/ja2tUWE.jpg",
    },
    "16": {
        "card_meaning": "Kararsızlık, seçimler, ateşkes, çıkmaz, engellenmiş duygular",
        "card_name": "Two of Swords",
        "card_url": "http://www.tarotlore.com/tarot-cards/two-of-swords/",
        "card_img": "http://i.imgur.com/EBIjsot.jpg",
    },
    "17": {
        "card_meaning": "Acılı ayrılık, üzüntü kalp kırıklığı, keder, reddedilme",
        "card_name": "Three of Swords",
        "card_url": "http://www.tarotlore.com/tarot-cards/three-of-swords/",
        "card_img": "http://i.imgur.com/CkKUNSa.jpg",
    },
    "18": {
        "card_meaning": "Tefekkür, iyileşme, pasiflik, gevşeme, dinlenme",
        "card_name": "Four of Swords",
        "card_url": "http://www.tarotlore.com/tarot-cards/four-of-swords/",
        "card_img": "http://i.imgur.com/y1psOrh.jpg",
    },
    "19": {
        "card_meaning": "Çatışma, gerilim, kayıp, yenilgi, ne pahasına olursa olsun kazanma, ihanet",
        "card_name": "Five of Swords",
        "card_url": "http://www.tarotlore.com/tarot-cards/five-of-swords/",
        "card_img": "http://i.imgur.com/T1pDWbo.jpg",
    },
    "2": {
        "card_meaning": "Gelecek planlama, ilerleme, kararlar, keşif",
        "card_name": "Two of Wands",
        "card_url": "http://www.tarotlore.com/tarot-cards/two-of-wands/",
        "card_img": "http://i.imgur.com/Ghb63pd.jpg",
    },
    "20": {
        "card_meaning": "Üzücü ama gerekli geçiş, geçiş ayini",
        "card_name": "Six of Swords",
        "card_url": "http://www.tarotlore.com/tarot-cards/six-of-swords/",
        "card_img": "http://i.imgur.com/ddXLubY.jpg",
    },
    "21": {
        "card_meaning": "İhanet, aldatma, bir şeyden kurtulma, gizlilik",
        "card_name": "Seven of Swords",
        "card_url": "http://www.tarotlore.com/tarot-cards/seven-of-swords/",
        "card_img": "http://i.imgur.com/6DNu8dU.jpg",
    },
    "22": {
        "card_meaning": "İzolasyon, kendi kendine uygulanan kısıtlama, hapis",
        "card_name": "Eight of Swords",
        "card_url": "http://www.tarotlore.com/tarot-cards/eight-of-swords/",
        "card_img": "http://i.imgur.com/ov9j8pg.jpg",
    },
    "23": {
        "card_meaning": "Depresyon, kabuslar, yoğun kaygı, umutsuzluk",
        "card_name": "Nine of Swords",
        "card_url": "http://www.tarotlore.com/tarot-cards/nine-of-swords/",
        "card_img": "http://i.imgur.com/iWl54Xx.jpg",
    },
    "24": {
        "card_meaning": "Sırttan bıçaklanma, yenilgi, kriz, ihanet, sonlar, kayıp",
        "card_name": "Ten of Swords",
        "card_url": "http://www.tarotlore.com/tarot-cards/ten-of-swords/",
        "card_img": "http://i.imgur.com/NhkCBnz.jpg",
    },
    "25": {
        "card_meaning": "Konuşkan, meraklı, zihinsel olarak huzursuz, enerjik",
        "card_name": "Page of Swords",
        "card_url": "http://www.tarotlore.com/tarot-cards/page-of-swords/",
        "card_img": "http://i.imgur.com/decjazD.jpg",
    },
    "26": {
        "card_meaning": "Fikir sahibi, aceleci, eylem odaklı, iletişimsel",
        "card_name": "Knight of Swords",
        "card_url": "http://www.tarotlore.com/tarot-cards/knight-of-swords/",
        "card_img": "http://i.imgur.com/p87LNk8.jpg",
    },
    "27": {
        "card_meaning": "Hızlı düşünen, organize, anlayışlı, bağımsız",
        "card_name": "Queen of Swords",
        "card_url": "http://www.tarotlore.com/tarot-cards/queen-of-swords/",
        "card_img": "http://i.imgur.com/vgTOeBk.jpg",
    },
    "28": {
        "card_meaning": "Açık düşünme, entelektüel güç, otorite, hakikat",
        "card_name": "King of Swords",
        "card_url": "http://www.tarotlore.com/tarot-cards/king-of-swords/",
        "card_img": "http://i.imgur.com/Y0EtbYp.jpg",
    },
    "29": {
        "card_meaning": "Aşk, şefkat, yaratıcılık, ezici duygu",
        "card_name": "Ace of Cups",
        "card_url": "http://www.tarotlore.com/tarot-cards/ace-of-cups/",
        "card_img": "http://i.imgur.com/4ZcxuXf.jpg",
    },
    "3": {
        "card_meaning": "Hazırlık, öngörü, girişim, genişleme",
        "card_name": "Three of Wands",
        "card_url": "http://www.tarotlore.com/tarot-cards/three-of-wands/",
        "card_img": "http://i.imgur.com/NIUAuzw.jpg",
    },
    "30": {
        "card_meaning": "Birleşik aşk, ortaklık, cazibe, ilişkiler",
        "card_name": "Two of Cups",
        "card_url": "http://www.tarotlore.com/tarot-cards/two-of-cups/",
        "card_img": "http://i.imgur.com/K8MRy5I.jpg",
    },
    "31": {
        "card_meaning": "Kutlama, dostluk, yaratıcılık, topluluk",
        "card_name": "Three of Cups",
        "card_url": "http://www.tarotlore.com/tarot-cards/three-of-cups/",
        "card_img": "http://i.imgur.com/lqsvyuD.jpg",
    },
    "32": {
        "card_meaning": "Meditasyon, tefekkür, ilgisizlik, yeniden değerlendirme",
        "card_name": "Four of Cups",
        "card_url": "http://www.tarotlore.com/tarot-cards/four-of-cups/",
        "card_img": "http://i.imgur.com/wd1JMK5.jpg",
    },
    "33": {
        "card_meaning": "Kayıp, pişmanlık, hayal kırıklığı, umutsuzluk, yas",
        "card_name": "Five of Cups",
        "card_url": "http://www.tarotlore.com/tarot-cards/five-of-cups/",
        "card_img": "http://i.imgur.com/8EqDUAa.jpg",
    },
    "34": {
        "card_meaning": "Yeniden birleşme, nostalji, çocukluk anıları, masumiyet",
        "card_name": "Six of Cups",
        "card_url": "http://www.tarotlore.com/tarot-cards/six-of-cups/",
        "card_img": "http://i.imgur.com/pA7oFHJ.jpg",
    },
    "35": {
        "card_meaning": "Fantezi, illüzyon, hüsnükuruntu, seçimler, hayal gücü",
        "card_name": "Seven of Cups",
        "card_url": "http://www.tarotlore.com/tarot-cards/seven-of-cups/",
        "card_img": "http://i.imgur.com/NL300h2.jpg",
    },
    "36": {
        "card_meaning": "Kaçış, hayal kırıklığı, terk, geri çekilme",
        "card_name": "Eight of Cups",
        "card_url": "http://www.tarotlore.com/tarot-cards/eight-of-cups/",
        "card_img": "http://i.imgur.com/MTgZYuZ.jpg",
    },
    "37": {
        "card_meaning": "Dileklerin yerine getirilmesi, rahatlık, mutluluk, memnuniyet",
        "card_name": "Nine of Cups",
        "card_url": "http://www.tarotlore.com/tarot-cards/nine-of-cups/",
        "card_img": "http://i.imgur.com/FzW2aGy.jpg",
    },
    "38": {
        "card_meaning": "Uyum, evlilik, mutluluk, uyum",
        "card_name": "Ten of Cups",
        "card_url": "http://www.tarotlore.com/tarot-cards/ten-of-cups/",
        "card_img": "http://i.imgur.com/bEm3wa8.jpg",
    },
    "39": {
        "card_meaning": "Bir haberci, yaratıcı başlangıçlar, eşzamanlılık",
        "card_name": "Page of Cups",
        "card_url": "http://www.tarotlore.com/tarot-cards/page-of-cups/",
        "card_img": "http://i.imgur.com/UvanQ1x.jpg",
    },
    "4": {
        "card_meaning": "Kutlama, uyum, evlilik, ev, topluluk",
        "card_name": "Four of Wands",
        "card_url": "http://www.tarotlore.com/tarot-cards/four-of-wands/",
        "card_img": "http://i.imgur.com/heelDVY.jpg",
    },
    "40": {
        "card_meaning": "Romantizm, çekicilik, 'Parlayan zırhlı şövalye', hayal gücü",
        "card_name": "Knight of Cups",
        "card_url": "http://www.tarotlore.com/tarot-cards/knight-of-cups/",
        "card_img": "http://i.imgur.com/SfpE4cm.jpg",
    },
    "41": {
        "card_meaning": "Duygusal güvenlik, sakin, sezgisel, şefkatli",
        "card_name": "Queen of Cups",
        "card_url": "http://www.tarotlore.com/tarot-cards/queen-of-cups/",
        "card_img": "http://i.imgur.com/ZVMpaO6.jpg",
    },
    "42": {
        "card_meaning": "Duygusal denge ve kontrol, cömertlik",
        "card_name": "King of Cups",
        "card_url": "http://www.tarotlore.com/tarot-cards/king-of-cups/",
        "card_img": "http://i.imgur.com/fW2cZDl.jpg",
    },
    "43": {
        "card_meaning": "Tezahür, yeni finansal fırsat, refah",
        "card_name": "Ace of Pentacles",
        "card_url": "http://www.tarotlore.com/tarot-cards/ace-of-pentacles/",
        "card_img": "http://i.imgur.com/ebAyNZZ.jpg",
    },
    "44": {
        "card_meaning": "Denge, uyarlanabilirlik, zaman yönetimi, önceliklendirme",
        "card_name": "Two of Pentacles",
        "card_url": "http://www.tarotlore.com/tarot-cards/two-of-pentacles/",
        "card_img": "http://i.imgur.com/F3URp9M.jpg",
    },
    "45": {
        "card_meaning": "Takım çalışması, ilk gerçekleştirme, işbirliği, öğrenme",
        "card_name": "Three of Pentacles",
        "card_url": "http://www.tarotlore.com/tarot-cards/three-of-pentacles/",
        "card_img": "http://i.imgur.com/hzIo13n.jpg",
    },
    "46": {
        "card_meaning": "Kontrol, istikrar, güvenlik, sahiplik, muhafazakarlık",
        "card_name": "Four of Pentacles",
        "card_url": "http://www.tarotlore.com/tarot-cards/four-of-pentacles/",
        "card_img": "http://i.imgur.com/caXXbBL.jpg",
    },
    "47": {
        "card_meaning": "İzolasyon, güvensizlik, endişe, finansal kayıp, yoksulluk",
        "card_name": "Five of Pentacles",
        "card_url": "http://www.tarotlore.com/tarot-cards/five-of-pentacles/",
        "card_img": "http://i.imgur.com/hIG43wQ.jpg",
    },
    "48": {
        "card_meaning": "Cömertlik, hayırseverlik, verme, refah, zenginliği paylaşma",
        "card_name": "Six of Pentacles",
        "card_url": "http://www.tarotlore.com/tarot-cards/six-of-pentacles/",
        "card_img": "http://i.imgur.com/NR2JdPf.jpg",
    },
    "49": {
        "card_meaning": "Vizyon, azim, kâr, ödül, yatırım",
        "card_name": "Seven of Pentacles",
        "card_url": "http://www.tarotlore.com/tarot-cards/seven-of-pentacles/",
        "card_img": "http://i.imgur.com/nYYBX2T.jpg",
    },
    "5": {
        "card_meaning": "Anlaşmazlık, rekabet, çekişme, gerginlik, çatışma",
        "card_name": "Five of Wands",
        "card_url": "http://www.tarotlore.com/tarot-cards/five-of-wands/",
        "card_img": "http://i.imgur.com/Qojm2p1.jpg",
    },
    "50": {
        "card_meaning": "Çıraklık, eğitim, kalite, bağlılık",
        "card_name": "Eight of Pentacles",
        "card_url": "http://www.tarotlore.com/tarot-cards/eight-of-pentacles/",
        "card_img": "http://i.imgur.com/rSCcjOv.jpg",
    },
    "51": {
        "card_meaning": "Şükran, lüks, kendi kendine yeterlilik, doruk noktası",
        "card_name": "Nine of Pentacles",
        "card_url": "http://www.tarotlore.com/tarot-cards/nine-of-pentacles/",
        "card_img": "http://i.imgur.com/TsHqgIQ.jpg",
    },
    "52": {
        "card_meaning": "Zenginlik, miras, aile, kuruluş, emeklilik",
        "card_name": "Ten of Pentacles",
        "card_url": "http://www.tarotlore.com/tarot-cards/ten-of-pentacles/",
        "card_img": "http://i.imgur.com/p8VSgOO.jpg",
    },
    "53": {
        "card_meaning": "Tezahür, finansal fırsat, yeni iş",
        "card_name": "Page of Pentacles",
        "card_url": "http://www.tarotlore.com/tarot-cards/page-of-pentacles/",
        "card_img": "http://i.imgur.com/WsQEzyQ.jpg",
    },
    "54": {
        "card_meaning": "Verimlilik, rutin, muhafazakarlık, metodik",
        "card_name": "Knight of Pentacles",
        "card_url": "http://www.tarotlore.com/tarot-cards/knight-of-pentacles/",
        "card_img": "http://i.imgur.com/yEL8ZAr.jpg",
    },
    "55": {
        "card_meaning": "Pratik, sade, anaç, gerçekçi, güvenlik",
        "card_name": "Queen of Pentacles",
        "card_url": "http://www.tarotlore.com/tarot-cards/queen-of-pentacles/",
        "card_img": "http://i.imgur.com/OX60YCi.jpg",
    },
    "56": {
        "card_meaning": "Güvenlik, kontrol, güç, disiplin, bolluk",
        "card_name": "King of Pentacles",
        "card_url": "http://www.tarotlore.com/tarot-cards/king-of-pentacles/",
        "card_img": "http://i.imgur.com/Dk6tR9R.jpg",
    },
    "57": {
        "card_meaning": "Başlangıçlar, masumiyet, kendiliğindenlik, özgür bir ruh",
        "card_name": "Fool",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-fool/",
        "card_img": "http://i.imgur.com/vetEoDu.jpg",
    },
    "58": {
        "card_meaning": "Güç, beceri, konsantrasyon, eylem, beceriklilik",
        "card_name": "Magician",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-magician/",
        "card_img": "http://i.imgur.com/9VJLy9S.jpg",
    },
    "59": {
        "card_meaning": "Sezgi, Yüksek güçler, gizem, bilinçaltı zihin",
        "card_name": "High Priestess",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-high-priestess/",
        "card_img": "http://i.imgur.com/bablzG8.jpg",
    },
    "6": {
        "card_meaning": "Halkın tanınması, zafer, ilerleme, kendine güven",
        "card_name": "Six of Wands",
        "card_url": "http://www.tarotlore.com/tarot-cards/six-of-wands/",
        "card_img": "http://i.imgur.com/DClClQ5.jpg",
    },
    "60": {
        "card_meaning": "Doğurganlık, kadınlık, güzellik, doğa, bolluk",
        "card_name": "Empress",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-empress/",
        "card_img": "http://i.imgur.com/sh0Fzdt.jpg",
    },
    "61": {
        "card_meaning": "Otorite, baba figürü, yapı, sağlam temel",
        "card_name": "Emperor",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-emperor/",
        "card_img": "http://i.imgur.com/sc76hNS.jpg",
    },
    "62": {
        "card_meaning": "Din, grup kimliği, uygunluk, gelenek, inançlar",
        "card_name": "Hierophant",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-hierophant/",
        "card_img": "http://i.imgur.com/JFvG1um.jpg",
    },
    "63": {
        "card_meaning": "Aşk, birlik, ilişkiler, değerler uyumu, seçimler",
        "card_name": "Lovers",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-lovers/",
        "card_img": "http://i.imgur.com/U6CcViS.jpg",
    },
    "64": {
        "card_meaning": "Kontrol, irade gücü, zafer, iddia, kararlılık",
        "card_name": "Chariot",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-chariot/",
        "card_img": "http://i.imgur.com/xilfsxU.jpg",
    },
    "65": {
        "card_meaning": "Strength, courage, patience, control, compassion",
        "card_name": "Strength",
        "card_url": "http://www.tarotlore.com/tarot-cards/strength/",
        "card_img": "http://i.imgur.com/DhNmgJ5.jpg",
    },
    "66": {
        "card_meaning": "Ruh arayışı, iç gözlem, yalnızlık, içsel rehberlik",
        "card_name": "Hermit",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-hermit/",
        "card_img": "http://i.imgur.com/yTzCitM.jpg",
    },
    "67": {
        "card_meaning": "İyi şanslar, karma, yaşam döngüleri, kader, bir dönüm noktası",
        "card_name": "Wheel of Fortune",
        "card_url": "http://www.tarotlore.com/tarot-cards/wheel-of-fortune/",
        "card_img": "http://i.imgur.com/jrY1gDP.jpg",
    },
    "68": {
        "card_meaning": "Adalet, hakkaniyet, hakikat, sebep ve sonuç, hukuk",
        "card_name": "Justice",
        "card_url": "http://www.tarotlore.com/tarot-cards/justice/",
        "card_img": "http://i.imgur.com/eyHEpUR.jpg",
    },
    "69": {
        "card_meaning": "Askıya alma, kısıtlama, salıverme, fedakarlık",
        "card_name": "Hanged Man",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-hanged-man/",
        "card_img": "http://i.imgur.com/b5Sml3N.jpg",
    },
    "7": {
        "card_meaning": "Meydan okuma, rekabet, azim",
        "card_name": "Seven of Wands",
        "card_url": "http://www.tarotlore.com/tarot-cards/seven-of-wands/",
        "card_img": "http://i.imgur.com/hsNtHC0.jpg",
    },
    "70": {
        "card_meaning": "Bitişler, başlangıçlar, değişim, dönüşüm, geçiş",
        "card_name": "Death",
        "card_url": "http://www.tarotlore.com/tarot-cards/death/",
        "card_img": "http://i.imgur.com/ujauT3a.jpg",
    },
    "71": {
        "card_meaning": "Denge, ölçülülük, sabır, amaç, anlam",
        "card_name": "Temperance",
        "card_url": "http://www.tarotlore.com/tarot-cards/temperance/",
        "card_img": "http://i.imgur.com/i2iwvA0.jpg",
    },
    "72": {
        "card_meaning": "Esaret, bağımlılık, cinsellik, materyalizm",
        "card_name": "Devil",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-devil/",
        "card_img": "http://i.imgur.com/ChhcGKF.jpg",
    },
    "73": {
        "card_meaning": "Felaket, kargaşa, ani değişim, vahiy",
        "card_name": "Tower",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-tower/",
        "card_img": "http://i.imgur.com/ZYpEMKl.jpg",
    },
    "74": {
        "card_meaning": "Umut, maneviyat, yenilenme, ilham, dinginlik",
        "card_name": "Star",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-star/",
        "card_img": "http://i.imgur.com/2X56bTd.jpg",
    },
    "75": {
        "card_meaning": "İllüzyon, korku, endişe, güvensizlik, bilinçaltı",
        "card_name": "Moon",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-moon/",
        "card_img": "http://i.imgur.com/8Cpfekc.jpg",
    },
    "76": {
        "card_meaning": "Eğlence, sıcaklık, başarı, pozitiflik, canlılık",
        "card_name": "Sun",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-sun/",
        "card_img": "http://i.imgur.com/zgJJy7b.jpg",
    },
    "77": {
        "card_meaning": "Yargılama, yeniden doğuş, içsel çağrı, bağışlanma",
        "card_name": "Judgement",
        "card_url": "http://www.tarotlore.com/tarot-cards/judgement/",
        "card_img": "http://i.imgur.com/JyALFQF.jpg",
    },
    "78": {
        "card_meaning": "Tamamlama, entegrasyon, başarı, seyahat",
        "card_name": "World",
        "card_url": "http://www.tarotlore.com/tarot-cards/the-world/",
        "card_img": "http://i.imgur.com/3ZncYkn.jpg",
    },
    "8": {
        "card_meaning": "Hız, aksiyon, hava yolculuğu, hareket, hızlı değişim",
        "card_name": "Eight of Wands",
        "card_url": "http://www.tarotlore.com/tarot-cards/eight-of-wands/",
        "card_img": "http://i.imgur.com/TaTYcNt.jpg",
    },
    "9": {
        "card_meaning": "Cesaret, sebat, inanç testi, dayanıklılık",
        "card_name": "Nine of Wands",
        "card_url": "http://www.tarotlore.com/tarot-cards/nine-of-wands/",
        "card_img": "http://i.imgur.com/qjJdi8J.jpg",
    },
}
